import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { DefaultProvider } from "@/components/default-provider";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Woovi Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={nunito.className}>
        <DefaultProvider>
          {children}
        </DefaultProvider>
      </body>
    </html>
  );
}
